# Generated by Django 2.1.2 on 2020-04-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='login',
        ),
        migrations.AlterField(
            model_name='employer',
            name='face',
            field=models.CharField(choices=[('A', 'Admin'), ('E', 'Employer'), ('S', 'Student')], default='A', max_length=3),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='face',
            field=models.CharField(choices=[('A', 'Admin'), ('E', 'Employer'), ('S', 'Student')], default='S', max_length=3),
        ),
    ]
