# Generated by Django 2.1.2 on 2020-04-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200411_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birth',
        ),
        migrations.AddField(
            model_name='employer',
            name='сс_approve',
            field=models.CharField(default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='face',
            field=models.CharField(choices=[('S', 'Student'), ('A', 'Admin'), ('E', 'Employer')], default='A', max_length=3),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('2', '2'), ('1', '1'), ('4', '4'), ('3', '3')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='face',
            field=models.CharField(choices=[('S', 'Student'), ('A', 'Admin'), ('E', 'Employer')], default='S', max_length=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='speciality',
            field=models.CharField(choices=[('IS', 'IS'), ('RET', 'RET'), ('CSSE', 'CSSE')], max_length=12),
        ),
    ]
