# Generated by Django 2.1.2 on 2020-04-11 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_auto_20200411_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(blank=True, max_length=72)),
                ('position', models.CharField(max_length=24)),
                ('phone', models.CharField(max_length=12)),
                ('сс_approve', models.CharField(default='N', max_length=1, null=True)),
                ('face', models.CharField(choices=[('E', 'Employer'), ('S', 'Student'), ('A', 'Admin')], default='A', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(blank=True)),
                ('course', models.CharField(choices=[('4', '4'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('speciality', models.CharField(choices=[('IS', 'IS'), ('RET', 'RET'), ('CSSE', 'CSSE')], max_length=12)),
                ('phone', models.CharField(max_length=12)),
                ('face', models.CharField(choices=[('E', 'Employer'), ('S', 'Student'), ('A', 'Admin')], default='S', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
