# Generated by Django 2.1.2 on 2020-05-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200516_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('1', '1'), ('4', '4')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='speciality',
            field=models.CharField(choices=[('IS', 'IS'), ('CSSE', 'CSSE'), ('RET', 'RET')], max_length=12),
        ),
    ]
